name: Scoop
on:
  push:
    paths:
      - '.github/workflows/scoop.yml'
      - 'windows/scoop/**'

env:
  SCOOP: 'C:\bin'

defaults:
  run:
    shell: powershell
    working-directory: windows/scoop

jobs:
  scoop:
    name: Install App Bundle
    runs-on: windows-latest
    strategy:
      matrix:
        bundle: ['bn-dev', 'bn-ops', 'bn-common']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Scoop
        run: iex "& {$(irm get.scoop.sh)} -RunAsAdmin"

      - name: Add shims to path
        run: echo "C:\bin\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install packages
        run: .\bin\import.ps1 ${{ matrix.bundle }}


      - name: Get list of apps
        run: scoop list


