name: Scoop
on:
  push:
    paths:
      - '.github/workflows/scoop.yml'
      - 'windows/scoop/**'
jobs:
  vscode:
    name: Install Scoop and packages
    runs-on: windows-2022
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install packages
        shell: powershell
        run: |
          iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/bn-digital/home/latest/windows/scoop/import.ps1'))
          scoop bucket list
          scoop list
          npm --version
          node --version
          kubectl version
          helm version
          skaffold version
          doctl version