name: Scoop
on:
  push:
    paths:
      - '.github/workflows/scoop.yml'
      - 'windows/scoop/**'
jobs:
  vscode:
    name: Install Scoop and packages
    runs-on: windows-2022
    strategy:
      matrix:
        bundle: ['bn-dev', 'bn-ops', 'bn-common']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        
      - name: Install Scoop
        run: iex "& {$(irm get.scoop.sh)} -RunAsAdmin

      - name: Install packages
        shell: powershell
        working-directory: windows/scoop
        run: |
          .\import.ps1 ${{ matrix.bundle }}
          scoop bucket list
          scoop list
