name: Chocolatey
on:
  push:
    paths:
      - 'windows/scoop/**'
jobs:
  vscode:
    name: Install Scoop and packages
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install packages
        shell: powershell
        run: windows\scoop\import.ps1

      - name: Verify install
        shell: powershell
        run: scoop info nodejs
