name: Scoop
on:
  push:
    branches:
      - latest
    paths:
      - '.github/workflows/scoop.yml'
      - 'windows/scoop/apps/**'
      - 'windows/scoop/bin/**'

concurrency: 
  group: scoop
  cancel-in-progress: true
  
env:
  SCOOP: 'C:\bin'

jobs:
  verify:
    name: App Bundles
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
        working-directory: windows/scoop
    strategy:
      matrix:
        bundle: ['bn-dev', 'bn-ops', 'bn-common']
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Scoop
        run: iex "& {$(irm get.scoop.sh)} -RunAsAdmin"

      - name: Add shims to path
        run: echo "C:\bin\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install packages
        run: .\bin\import.ps1 ${{ matrix.bundle }}

      - name: Get list of apps
        run: scoop list

  publish:
    name: App Manifests
    needs: [verify]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Read from Vault
        uses: hashicorp/vault-action@v2.4.0
        with:
          method: github
          url: ${{ secrets.VAULT_PUBLIC_URL }}
          githubToken: ${{ secrets.BN_GITHUB_TOKEN }}
          secrets: |
            infrastructure/data/spaces            access-key-id         | S3_ACCESS_KEY_ID           ;
            infrastructure/data/spaces            secret-access-key     | S3_SECRET_ACCESS_KEY       ;

      - name: Upload S3
        uses: betahuhn/do-spaces-action@v2
        with:
          access_key: ${{ env.S3_ACCESS_KEY_ID }}
          secret_key: ${{ env.S3_SECRET_ACCESS_KEY }}
          space_name: bn-digital
          space_region: fra1
          source: windows/scoop/apps
          out_dir: scoop/apps


